artifactory:
  ## Artifactory license.
  license:
    secret: jpdlicense
    ## The dataKey should be the name of the secret data key created.
    dataKey: licensekey
    
  ## Create configMap with artifactory.config.import.xml and security.import.xml and pass name of configMap in following parameter
  configMapName: jpd-config-import

  ## List of secrets for Artifactory user plugins.
  ## One Secret per plugin's files.
  # userPluginSecrets:
  #  - archive-old-artifacts
  #  - build-cleanup
  #  - webhook
  #  - '{{ template "my-chart.fullname" . }}'
