global:
  jfrogUrl: https://jpd.workshops.zone 
  jfrogUrlUI: https://jpd.workshops.zone 
  # certificates added to this secret will be copied to $JFROG_HOME/<product>/var/etc/security/keys/trusted directory
  customCertificates:
    enabled: true
    certificateSecretName: jpd-tls                 

artifactory:
  enabled: true
  artifactory:
    # Note: For HA deployments, set replicaCount >1 (recommended 3)
    replicaCount: 1
    license:
      secret: artifactory-cluster-license
      dataKey: art.lic

xray:
  enabled: false
insight:
  enabled: false 
distribution:
  enabled: false
pipelines:
  enabled: false
rabbitmq:
  enabled: false
redis:
  enabled: false
      


